import { test, expect } from "@playwright/test";
import type { Market, User, Currency } from "../types";
//PB NOTES: "../" search at folder level. "." search at root level
import marketJson from "../data/markets.json" with { type: "json" };
import usersJson from "../data/users.json" with { type: "json" };
import { TIMEOUT } from "node:dns";

const markets = marketJson as Market[];
const users = usersJson as User[];

const standardUser = users.find((u) => u.username === "standard_user");
//PB NOTE: The expression "u" can be replaced by "user" it doesn't affect abything, this is the name of the function.

//PB NOTE: A "Guard Clause" is a piece of conditional logic placed at the very beginning of a function to check for invalid conditions
//  or edge cases and immediately exit. If an invalid state or incorrect input parameter is detected, the function returns early or
//  throws an exception. This prevents the execution of the rest of the function and avoids wrapping the core logic inside heavily
//  nested if-else blocks

if (!standardUser) {
  throw new Error("data/users.json doesn't include a username called standard_user");
}

/*
  //PB NOTE: The Guard Clause above, it's replacing the code below
if (standardUser){
    users.find((u) => u.username === "standard_user")
}
else{
    throw new Error("data/users.json doesn't include a username called standard_user")
}
*/

const currencySymbol: Partial<Record<Currency, string>> = {
  MXN: "$",
  JPY: "¥",
};
// "Record" it's a generic that use a key value and can be used to save values.
//PB NOTE: If I were not using "Partial < >", then I{ll be getting an error in the method "currencySymbol", once I was not specifying
//  USD and CHF, partial allows to define only some of the specified ones
test.describe("Parametrized smoke per market", () => {
  for (const market of markets) {
    //PB NOTE: "String Interpolation" is a programming technique that allows you to embed variables or expressions directly inside a
    // string literal. Instead of manually gluing text together, you use placeholders that the programming language automatically
    // replaces with their actual values at runtime
    //PB NOTE: When using a "tag", never forget to addd the "@" before the tags.
    test(`TC-${market.code} - login + catalog in market ${market.code}`, { tag: "@smoke" }, async ({ page }) => {
      // ARRANGE
      await page.goto("/");

      // ACT
      await page.getByTestId("username-desktop").fill(standardUser.username);
      await page.getByTestId("password-desktop").fill(standardUser.password);

      await page.getByTestId(`market-${market.code}`).click();

      await page.getByTestId("login-button-desktop").click();

      // ASSERT
      await expect(page).toHaveURL(/\/catalog/);

      const pizzaCards = page.locator("[data-testid^='pizza-card-p']");
      await expect(pizzaCards.first()).toBeVisible({ timeout: 30_000 });

      const allCards = await pizzaCards.all();
      await expect(allCards.length).toBeGreaterThanOrEqual(12);
      //PB NOTE: The line above might have or not "await" at the beggining, it doesn't affect the code at all.
    });
  }

  test("test generated by codegen 1", async ({ page }) => {
    await page.goto("https://omnipizza-frontend.onrender.com/");
    await page.getByTestId("username-desktop").click({ timeout: 30_000 });
    await page.getByTestId("market-MX").click();
    await page.getByTestId("password-desktop").click();
    await page.getByTestId("login-button-desktop").click();
    await expect(page.getByTestId("cart-sidebar-empty")).toContainText("Tu carrito está vacío.");
  });

  //PB NOTE: we can perform special aciton on the tests, we need to add a text in the test signature
  // test.skip indicates that the test must be "skipped"
  // test.only indicates that "only" this test must be executed, to AVOIDM getting an error with "only" make sure that you have disbled
  //  the next command "forbidOnly: !!process.env.CI,"
  test("test generated by codegen 2", async ({ page }) => {
    await page.goto("https://omnipizza-frontend.onrender.com/");
    await page.getByTestId("user-locked_out_user").click();
    await page.getByTestId("market-CH").click();
    await page.getByTestId("login-button-desktop").click();
    await expect(page.getByTestId("login-error")).toContainText("Invalid");
  });

  test("Locators Reference", async ({page}) => {
    await page.goto("https://omnipizza-frontend.onrender.com/");
    //await page.getByRole("button", {name: "Sign In"}).click();
    //PB NOTE: getByRole, helps to retrieve elements from DOM, basd on how the system identify the object like "alert", "button",
    //  "checkbox", "columnheader", "combobox", "dialog", "form", "heading", "img", "link", "list", "listbox", "listitem", "paragraph",
    //  "progressbar", "radio", "radiogroup", "row","scrollbar", "search", "searchbox", "separator", "slider", "strong", "subscript",
    //  "superscript", "switch", "tab", "table", "tablist", "tabpanel", etc.
    //  Also there are multiple options that can be also applied in the getByRole, like checked, description, RegExp, number, name,
    //  pressed, selected, etc.
    const welcomeHeading = page.getByRole("heading", { name: "Welcome back!",level: 2 });
    //console.log(await welcomeHeading.innerHTML()); //Print the "Welcome back!" message
    //console.log(await welcomeHeading.textContent()); //Print the "Welcome back!" message

    const craftText = page.getByRole("heading", { level: 1 });
    console.log(await craftText.textContent());

    await page.getByRole("textbox", { name: "standard_user" }).fill("locked_out_user");

    await page.getByPlaceholder("standard_user").fill("problem_user");
    await page.getByPlaceholder("••••••••").fill("pizza123");

    const userNameLabel = page.getByText("Username");
    console.log(await userNameLabel.textContent());

    const pleaseEnterDetails = page.getByText("Please enter your details.", {exact: true});
     //PB NOTE: If we use "exact", the text must be exact, if I use the text as "Please enter your details", the line will fail
    console.log(await pleaseEnterDetails.innerHTML());

    await page.getByRole("button", { name: /sign in/i }).click();
  });

  test("More Locators", async ({page}) => {    
    // ARRANGE
    await page.goto("/");

    // ACT
    await page.getByTestId("username-desktop").fill(standardUser.username);
    await page.getByTestId("password-desktop").fill(standardUser.password);

    await page.getByTestId("market-MX").click();

    await page.getByTestId("login-button-desktop").click();

    const pepperoniPizza = page.getByAltText("Pepperoni");
    expect(pepperoniPizza).toHaveAttribute('alt',/Pepp/);

    const pizzaCards = page.locator("[data-testid^='pizza-card-']");
    await expect(pizzaCards.nth(2)).toBeVisible();
    await expect(pizzaCards.filter({hasText: "Pepperoni"})).toBeVisible();

    await expect(page.getByRole("heading", { level: 3 }).filter({hasText: "Quesos"})).toBeVisible();
    

    await page.getByRole("link", { name: "Finalizar Compra"}).click();
    // ASSERT
    //await expect(page).toHaveURL(/\/catalog/);
  });
});